import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from 'react';
import { CollapseProvider } from './hooks/collapseState';

// Load Geist Sans font from Google Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Load Geist Mono font from Google Fonts
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the Next.js app (used for SEO and browser tab info)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout component that wraps the entire app
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Renders the HTML structure, applies fonts, and provides the Collapse context to all children
  return (
    <html lang="en">
      <head>
        {/* Link to Material Symbols font for icon */}
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Provide collapse sidebar context to the whole app */}
        <CollapseProvider>
          {children}
        </CollapseProvider>
      </body>
    </html>
  );
}
